# E-Commerce Intelligence System

## 01 — Data Profiling

### Objective

Understand the structure, quality, and relationships of the raw Olist e-commerce datasets before performing data cleaning, transformation, and analysis.

### Dataset

Olist Brazilian E-Commerce Public Dataset

### Phase

Phase 1 — Data Profiling

In [17]:
from pathlib import Path
import pandas as pd
import numpy as np

In [18]:
DATA_DIR = Path("../data/raw")

In [19]:
DATA_DIR.exists()

True

In [20]:
csv_files = sorted(DATA_DIR.glob("*.csv"))

print(f"Number of CSV files: {len(csv_files)}")

for file in csv_files:
    print(file.name)

Number of CSV files: 9
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_orders_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [21]:
tables = {}

for file in csv_files:
    table_name = file.stem
    tables[table_name] = pd.read_csv(file)

In [22]:
tables

{'olist_customers_dataset':                             customer_id                customer_unique_id  \
 0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
 1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
 2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
 3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
 4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
 ...                                 ...                               ...
 99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
 99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
 99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
 99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
 99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

        customer_zip_code_prefix          customer_city customer_state
 0                         14409                 franca             SP
 1                          9790  sao bernardo do campo             SP
 2                          1151              sao paulo             SP
 3                          8775        mogi das cruzes             SP
 4                         13056               campinas             SP
 ...                         ...                    ...            ...
 99436                      3937              sao paulo             SP
 99437                      6764        taboao da serra             SP
 99438                     60115              fortaleza             CE
 99439                     92120                 canoas             RS
 99440                      6703                  cotia             SP

 [99441 rows x 5 columns],
 'olist_geolocation_dataset':          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
 0                               1037       -23.545621       -46.639292
 1                               1046       -23.546081       -46.644820
 2                               1046       -23.546129       -46.642951
 3                               1041       -23.544392       -46.639499
 4                               1035       -23.541578       -46.641607
 ...                              ...              ...              ...
 1000158                        99950       -28.068639       -52.010705
 1000159                        99900       -27.877125       -52.224882
 1000160                        99950       -28.071855       -52.014716
 1000161                        99980       -28.388932       -51.846871
 1000162                        99950       -28.070104       -52.018658

         geolocation_city geolocation_state
 0              sao paulo                SP
 1              sao paulo                SP
 2              sao paulo                SP
 3              sao paulo                SP
 4              sao paulo                SP
 ...                  ...               ...
 1000158         tapejara                RS
 1000159   getulio vargas                RS
 1000160         tapejara                RS
 1000161  david canabarro                RS
 1000162         tapejara                RS

 [1000163 rows x 5 columns],
 'olist_order_items_dataset':                                 order_id  order_item_id  \
 0       00010242fe8c5a6d1ba2dd792cb16214              1
 1       00018f77f2f0320c557190d7a144bdd3              1
 2       000229ec398224ef6ca0657da4fc703e              1
 3       00024acbcdf0a6daa1e931b038114c75              1
 4       00042b26cf59d7ce69dfabb4e55b4fd9              1
 ...                                  ...            ...
 112645  fffc94f6ce00a00581880bf54a75a037              1
 112646  fffcd46ef2263f404302a634eb57f7eb              1
 112647  fffce4705a9662cd70adb13d4a31832d              1
 112648  fffe18544ffabc95dfada21779c9644f              1
 112649  fffe41c64501cc87c801fd61db3f6244              1

                               product_id                         seller_id  \
 0       4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
 1       e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
 2       c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
 3       7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
 4       ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
 ...                                  ...                               ...
 112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
 112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
 112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
 112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
 112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

         shipping_limit_date   price  freight_value
 0       2017-09-19 09:45:35   58.90          13.29
 1       2017-05-03 11:05:13  239.90          19.93
 2       2018-01-18 14:48:30  199.00          17.87
 3       2018-08-15 10:10:18   12.99          12.79
 4       2017-02-13 13:57:51  199.90          18.14
 ...                     ...     ...            ...
 112645  2018-05-02 04:11:01  299.99          43.41
 112646  2018-07-20 04:31:48  350.00          36.53
 112647  2017-10-30 17:14:25   99.90          16.95
 112648  2017-08-21 00:04:32   55.99           8.72
 112649  2018-06-12 17:10:13   43.00          12.79

 [112650 rows x 7 columns],
 'olist_order_payments_dataset':                                 order_id  payment_sequential payment_type  \
 0       b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
 1       a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
 2       25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
 3       ba78997921bbcdc1373bb41e913ab953                   1  credit_card
 4       42fdf880ba16b47b59251dd489d4441a                   1  credit_card
 ...                                  ...                 ...          ...
 103881  0406037ad97740d563a178ecc7a2075c                   1       boleto
 103882  7b905861d7c825891d6347454ea7863f                   1  credit_card
 103883  32609bbb3dd69b3c066a6860554a77bf                   1  credit_card
 103884  b8b61059626efa996a60be9bb9320e10                   1  credit_card
 103885  28bbae6599b09d39ca406b747b6632b1                   1       boleto

         payment_installments  payment_value
 0                          8          99.33
 1                          1          24.39
 2                          1          65.71
 3                          8         107.78
 4                          2         128.45
 ...                      ...            ...
 103881                     1         363.31
 103882                     2          96.80
 103883                     1          47.77
 103884                     5         369.54
 103885                     1         191.58

 [103886 rows x 5 columns],
 'olist_order_reviews_dataset':                               review_id                          order_id  \
 0      7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
 1      80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
 2      228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
 3      e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
 4      f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1
 ...                                 ...                               ...
 99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
 99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
 99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
 99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
 99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

        review_score review_comment_title  \
 0                 4                  NaN
 1                 5                  NaN
 2                 5                  NaN
 3                 5                  NaN
 4                 5                  NaN
 ...             ...                  ...
 99219             5                  NaN
 99220             5                  NaN
 99221             5                  NaN
 99222             4                  NaN
 99223             1                  NaN

                                   review_comment_message review_creation_date  \
 0                                                    NaN  2018-01-18 00:00:00
 1                                                    NaN  2018-03-10 00:00:00
 2                                                    NaN  2018-02-17 00:00:00
 3                  Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
 4      Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00
 ...                                                  ...                  ...
 99219                                                NaN  2018-07-07 00:00:00
 99220                                                NaN  2017-12-09 00:00:00
 99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
 99222                                                NaN  2018-07-01 00:00:00
 99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

       review_answer_timestamp
 0         2018-01-18 21:46:59
 1         2018-03-11 03:05:13
 2         2018-02-18 14:36:24
 3         2017-04-21 22:02:06
 4         2018-03-02 10:26:53
 ...                       ...
 99219     2018-07-14 17:18:30
 99220     2017-12-11 20:06:42
 99221     2018-03-23 09:10:43
 99222     2018-07-02 12:59:13
 99223     2017-07-03 21:01:49

 [99224 rows x 7 columns],
 'olist_orders_dataset':                                order_id                       customer_id  \
 0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
 1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
 2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
 3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
 4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
 ...                                 ...                               ...
 99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
 99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
 99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
 99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
 99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

       order_status order_purchase_timestamp    order_approved_at  \
 0        delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
 1        delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
 2        delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
 3        delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
 4        delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
 ...            ...                      ...                  ...
 99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
 99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
 99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
 99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
 99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

       order_delivered_carrier_date order_delivered_customer_date  \
 0              2017-10-04 19:55:00           2017-10-10 21:25:13
 1              2018-07-26 14:31:00           2018-08-07 15:27:45
 2              2018-08-08 13:50:00           2018-08-17 18:06:29
 3              2017-11-22 13:39:59           2017-12-02 00:28:42
 4              2018-02-14 19:46:34           2018-02-16 18:17:02
 ...                            ...                           ...
 99436          2017-03-10 11:18:03           2017-03-17 15:08:01
 99437          2018-02-07 23:22:42           2018-02-28 17:37:56
 99438          2017-08-28 20:52:26           2017-09-21 11:24:17
 99439          2018-01-12 15:35:03           2018-01-25 23:32:54
 99440          2018-03-09 22:11:59           2018-03-16 13:08:30

       order_estimated_delivery_date
 0               2017-10-18 00:00:00
 1               2018-08-13 00:00:00
 2               2018-09-04 00:00:00
 3               2017-12-15 00:00:00
 4               2018-02-26 00:00:00
 ...                             ...
 99436           2017-03-28 00:00:00
 99437           2018-03-02 00:00:00
 99438           2017-09-27 00:00:00
 99439           2018-02-15 00:00:00
 99440           2018-04-03 00:00:00

 [99441 rows x 8 columns],
 'olist_products_dataset':                              product_id              product_category_name  \
 0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
 1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
 2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
 3      cef67bcfe19066a932b7673e239eb23d                              bebes
 4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
 ...                                 ...                                ...
 32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
 32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
 32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
 32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
 32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

        product_name_lenght  product_description_lenght  product_photos_qty  \
 0                     40.0                       287.0                 1.0
 1                     44.0                       276.0                 1.0
 2                     46.0                       250.0                 1.0
 3                     27.0                       261.0                 1.0
 4                     37.0                       402.0                 4.0
 ...                    ...                         ...                 ...
 32946                 45.0                        67.0                 2.0
 32947                 41.0                       971.0                 1.0
 32948                 50.0                       799.0                 1.0
 32949                 60.0                       156.0                 2.0
 32950                 58.0                       309.0                 1.0

        product_weight_g  product_length_cm  product_height_cm  \
 0                 225.0               16.0               10.0
 1                1000.0               30.0               18.0
 2                 154.0               18.0                9.0
 3                 371.0               26.0                4.0
 4                 625.0               20.0               17.0
 ...                 ...                ...                ...
 32946           12300.0               40.0               40.0
 32947            1700.0               16.0               19.0
 32948            1400.0               27.0                7.0
 32949             700.0               31.0               13.0
 32950            2083.0               12.0                2.0

        product_width_cm
 0                  14.0
 1                  20.0
 2                  15.0
 3                  26.0
 4                  13.0
 ...                 ...
 32946              40.0
 32947              16.0
 32948              27.0
 32949              20.0
 32950               7.0

 [32951 rows x 9 columns],
 'olist_sellers_dataset':                              seller_id  seller_zip_code_prefix  \
 0     3442f8959a84dea7ee197c632cb2df15                   13023
 1     d1b65fc7debc3361ea86b5f14c68d2e2                   13844
 2     ce3ad9de960102d0677a81f5d0bb7b2d                   20031
 3     c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
 4     51a04a8a6bdcb23deccc82b0b80742cf                   12914
 ...                                ...                     ...
 3090  98dddbc4601dd4443ca174359b237166                   87111
 3091  f8201cab383e484733266d1906e2fdfa                   88137
 3092  74871d19219c7d518d0090283e03c137                    4650
 3093  e603cf3fec55f8697c9059638d6c8eb5                   96080
 3094  9e25199f6ef7e7c347120ff175652c3b                   12051

             seller_city seller_state
 0              campinas           SP
 1            mogi guacu           SP
 2        rio de janeiro           RJ
 3             sao paulo           SP
 4     braganca paulista           SP
 ...                 ...          ...
 3090            sarandi           PR
 3091            palhoca           SC
 3092          sao paulo           SP
 3093            pelotas           RS
 3094            taubate           SP

 [3095 rows x 4 columns],
 'product_category_name_translation':             product_category_name product_category_name_english
 0                    beleza_saude                 health_beauty
 1          informatica_acessorios         computers_accessories
 2                      automotivo                          auto
 3                 cama_mesa_banho                bed_bath_table
 4                moveis_decoracao               furniture_decor
 ..                            ...                           ...
 66                         flores                       flowers
 67             artes_e_artesanato         arts_and_craftmanship
 68                fraldas_higiene           diapers_and_hygiene
 69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
 70             seguros_e_servicos         security_and_services

 [71 rows x 2 columns]}

In [23]:
tables.keys()

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_orders_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

In [24]:
tables["olist_orders_dataset"].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [25]:
tables.keys()

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_orders_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

In [26]:
dataset_inventory = []

for table_name, df in tables.items():
    dataset_inventory.append({
        "table": table_name,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

dataset_inventory = pd.DataFrame(dataset_inventory)

dataset_inventory

                               table     rows  columns
0            olist_customers_dataset    99441        5
1          olist_geolocation_dataset  1000163        5
2          olist_order_items_dataset   112650        7
3       olist_order_payments_dataset   103886        5
4        olist_order_reviews_dataset    99224        7
5               olist_orders_dataset    99441        8
6             olist_products_dataset    32951        9
7              olist_sellers_dataset     3095        4
8  product_category_name_translation       71        2

## 2. Schema and Data Quality Profiling

We inspect each table's columns, data types, missing values, and cardinality.

In [27]:
def profile_table(df, table_name):
    profile = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "non_null": df.notna().sum().values,
        "missing": df.isna().sum().values,
        "missing_pct": (df.isna().mean() * 100).round(2).values,
        "unique": df.nunique().values
    })

    print(f"Table: {table_name}")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")
    print(f"Duplicate rows: {df.duplicated().sum():,}")

    return profile

In [28]:
orders = tables["olist_orders_dataset"]

orders_profile = profile_table(
    orders,
    "olist_orders_dataset"
)

orders_profile

Table: olist_orders_dataset
Rows: 99,441
Columns: 8
Duplicate rows: 0

,column,dtype,non_null,missing,missing_pct,unique
0,order_id,object,99441,0,0.00,99441
1,customer_id,object,99441,0,0.00,99441
2,order_status,object,99441,0,0.00,8
3,order_purchase_timestamp,object,99441,0,0.00,98875
4,order_approved_at,object,99281,160,0.16,90733
5,order_delivered_carrier_date,object,97658,1783,1.79,81018
6,order_delivered_customer_date,object,96476,2965,2.98,95664
7,order_estimated_delivery_date,object,99441,0,0.00,459

In [29]:
profiles = {}

for table_name, df in tables.items():
    profiles[table_name] = profile_table(df, table_name)

Table: olist_customers_dataset
Rows: 99,441
Columns: 5
Duplicate rows: 0
Table: olist_geolocation_dataset
Rows: 1,000,163
Columns: 5
Duplicate rows: 261,831
Table: olist_order_items_dataset
Rows: 112,650
Columns: 7
Duplicate rows: 0
Table: olist_order_payments_dataset
Rows: 103,886
Columns: 5
Duplicate rows: 0
Table: olist_order_reviews_dataset
Rows: 99,224
Columns: 7
Duplicate rows: 0
Table: olist_orders_dataset
Rows: 99,441
Columns: 8
Duplicate rows: 0
Table: olist_products_dataset
Rows: 32,951
Columns: 9
Duplicate rows: 0
Table: olist_sellers_dataset
Rows: 3,095
Columns: 4
Duplicate rows: 0
Table: product_category_name_translation
Rows: 71
Columns: 2
Duplicate rows: 0

In [30]:
for table_name, profile in profiles.items():
    print("\n" + "=" * 80)
    print(table_name)
    display(profile)

================================================================================
olist_customers_dataset

                     column   dtype  non_null  missing  missing_pct  unique
0               customer_id  object     99441        0          0.0   99441
1        customer_unique_id  object     99441        0          0.0   96096
2  customer_zip_code_prefix   int64     99441        0          0.0   14994
3             customer_city  object     99441        0          0.0    4119
4            customer_state  object     99441        0          0.0      27

================================================================================
olist_geolocation_dataset

,column,dtype,non_null,missing,missing_pct,unique
0,geolocation_zip_code_prefix,int64,1000163,0,0.0,19015
1,geolocation_lat,float64,1000163,0,0.0,717360
2,geolocation_lng,float64,1000163,0,0.0,717613
3,geolocation_city,object,1000163,0,0.0,8011
4,geolocation_state,object,1000163,0,0.0,27

================================================================================
olist_order_items_dataset

                column    dtype  non_null  missing  missing_pct  unique
0             order_id   object    112650        0          0.0   98666
1        order_item_id    int64    112650        0          0.0      21
2           product_id   object    112650        0          0.0   32951
3            seller_id   object    112650        0          0.0    3095
4  shipping_limit_date   object    112650        0          0.0   93318
5                price  float64    112650        0          0.0    5968
6        freight_value  float64    112650        0          0.0    6999

================================================================================
olist_order_payments_dataset

                 column    dtype  non_null  missing  missing_pct  unique
0              order_id   object    103886        0          0.0   99440
1    payment_sequential    int64    103886        0          0.0      29
2          payment_type   object    103886        0          0.0       5
3  payment_installments    int64    103886        0          0.0      24
4         payment_value  float64    103886        0          0.0   29077

================================================================================
olist_order_reviews_dataset

                    column   dtype  non_null  missing  missing_pct  unique
0                review_id  object     99224        0         0.00   98410
1                 order_id  object     99224        0         0.00   98673
2             review_score   int64     99224        0         0.00       5
3     review_comment_title  object     11568    87656        88.34    4527
4   review_comment_message  object     40977    58247        58.70   36159
5     review_creation_date  object     99224        0         0.00     636
6  review_answer_timestamp  object     99224        0         0.00   98248

================================================================================
olist_orders_dataset

,column,dtype,non_null,missing,missing_pct,unique
0,order_id,object,99441,0,0.00,99441
1,customer_id,object,99441,0,0.00,99441
2,order_status,object,99441,0,0.00,8
3,order_purchase_timestamp,object,99441,0,0.00,98875
4,order_approved_at,object,99281,160,0.16,90733
5,order_delivered_carrier_date,object,97658,1783,1.79,81018
6,order_delivered_customer_date,object,96476,2965,2.98,95664
7,order_estimated_delivery_date,object,99441,0,0.00,459

================================================================================
olist_products_dataset

                       column    dtype  non_null  missing  missing_pct  unique
0                  product_id   object     32951        0         0.00   32951
1       product_category_name   object     32341      610         1.85      73
2         product_name_lenght  float64     32341      610         1.85      66
3  product_description_lenght  float64     32341      610         1.85    2960
4          product_photos_qty  float64     32341      610         1.85      19
5            product_weight_g  float64     32949        2         0.01    2204
6           product_length_cm  float64     32949        2         0.01      99
7           product_height_cm  float64     32949        2         0.01     102
8            product_width_cm  float64     32949        2         0.01      95

================================================================================
olist_sellers_dataset

                   column   dtype  non_null  missing  missing_pct  unique
0               seller_id  object      3095        0          0.0    3095
1  seller_zip_code_prefix   int64      3095        0          0.0    2246
2             seller_city  object      3095        0          0.0     611
3            seller_state  object      3095        0          0.0      23

================================================================================
product_category_name_translation

,column,dtype,non_null,missing,missing_pct,unique
0,product_category_name,object,71,0,0.0,71
1,product_category_name_english,object,71,0,0.0,71

In [31]:
profiles = {}

for table_name, df in tables.items():
    profiles[table_name] = profile_table(df, table_name)

Table: olist_customers_dataset
Rows: 99,441
Columns: 5
Duplicate rows: 0
Table: olist_geolocation_dataset
Rows: 1,000,163
Columns: 5
Duplicate rows: 261,831
Table: olist_order_items_dataset
Rows: 112,650
Columns: 7
Duplicate rows: 0
Table: olist_order_payments_dataset
Rows: 103,886
Columns: 5
Duplicate rows: 0
Table: olist_order_reviews_dataset
Rows: 99,224
Columns: 7
Duplicate rows: 0
Table: olist_orders_dataset
Rows: 99,441
Columns: 8
Duplicate rows: 0
Table: olist_products_dataset
Rows: 32,951
Columns: 9
Duplicate rows: 0
Table: olist_sellers_dataset
Rows: 3,095
Columns: 4
Duplicate rows: 0
Table: product_category_name_translation
Rows: 71
Columns: 2
Duplicate rows: 0

In [32]:

for table_name, profile in profiles.items():
    print("\n" + "=" * 80)
    print(table_name)
    display(profile)

================================================================================
olist_customers_dataset

                     column   dtype  non_null  missing  missing_pct  unique
0               customer_id  object     99441        0          0.0   99441
1        customer_unique_id  object     99441        0          0.0   96096
2  customer_zip_code_prefix   int64     99441        0          0.0   14994
3             customer_city  object     99441        0          0.0    4119
4            customer_state  object     99441        0          0.0      27

================================================================================
olist_geolocation_dataset

,column,dtype,non_null,missing,missing_pct,unique
0,geolocation_zip_code_prefix,int64,1000163,0,0.0,19015
1,geolocation_lat,float64,1000163,0,0.0,717360
2,geolocation_lng,float64,1000163,0,0.0,717613
3,geolocation_city,object,1000163,0,0.0,8011
4,geolocation_state,object,1000163,0,0.0,27

================================================================================
olist_order_items_dataset

                column    dtype  non_null  missing  missing_pct  unique
0             order_id   object    112650        0          0.0   98666
1        order_item_id    int64    112650        0          0.0      21
2           product_id   object    112650        0          0.0   32951
3            seller_id   object    112650        0          0.0    3095
4  shipping_limit_date   object    112650        0          0.0   93318
5                price  float64    112650        0          0.0    5968
6        freight_value  float64    112650        0          0.0    6999

================================================================================
olist_order_payments_dataset

                 column    dtype  non_null  missing  missing_pct  unique
0              order_id   object    103886        0          0.0   99440
1    payment_sequential    int64    103886        0          0.0      29
2          payment_type   object    103886        0          0.0       5
3  payment_installments    int64    103886        0          0.0      24
4         payment_value  float64    103886        0          0.0   29077

================================================================================
olist_order_reviews_dataset

                    column   dtype  non_null  missing  missing_pct  unique
0                review_id  object     99224        0         0.00   98410
1                 order_id  object     99224        0         0.00   98673
2             review_score   int64     99224        0         0.00       5
3     review_comment_title  object     11568    87656        88.34    4527
4   review_comment_message  object     40977    58247        58.70   36159
5     review_creation_date  object     99224        0         0.00     636
6  review_answer_timestamp  object     99224        0         0.00   98248

================================================================================
olist_orders_dataset

,column,dtype,non_null,missing,missing_pct,unique
0,order_id,object,99441,0,0.00,99441
1,customer_id,object,99441,0,0.00,99441
2,order_status,object,99441,0,0.00,8
3,order_purchase_timestamp,object,99441,0,0.00,98875
4,order_approved_at,object,99281,160,0.16,90733
5,order_delivered_carrier_date,object,97658,1783,1.79,81018
6,order_delivered_customer_date,object,96476,2965,2.98,95664
7,order_estimated_delivery_date,object,99441,0,0.00,459

================================================================================
olist_products_dataset

                       column    dtype  non_null  missing  missing_pct  unique
0                  product_id   object     32951        0         0.00   32951
1       product_category_name   object     32341      610         1.85      73
2         product_name_lenght  float64     32341      610         1.85      66
3  product_description_lenght  float64     32341      610         1.85    2960
4          product_photos_qty  float64     32341      610         1.85      19
5            product_weight_g  float64     32949        2         0.01    2204
6           product_length_cm  float64     32949        2         0.01      99
7           product_height_cm  float64     32949        2         0.01     102
8            product_width_cm  float64     32949        2         0.01      95

================================================================================
olist_sellers_dataset

                   column   dtype  non_null  missing  missing_pct  unique
0               seller_id  object      3095        0          0.0    3095
1  seller_zip_code_prefix   int64      3095        0          0.0    2246
2             seller_city  object      3095        0          0.0     611
3            seller_state  object      3095        0          0.0      23

================================================================================
product_category_name_translation

,column,dtype,non_null,missing,missing_pct,unique
0,product_category_name,object,71,0,0.0,71
1,product_category_name_english,object,71,0,0.0,71

# 3. Relationship and Key Validation

Before joining or transforming the datasets, we validate primary-key candidates, foreign-key relationships, and table cardinality.

In [34]:
customers = tables["olist_customers_dataset"]
orders = tables["olist_orders_dataset"]

In [35]:
print("Customer rows:", len(customers))
print("Unique customer_id:", customers["customer_id"].nunique())
print("Duplicate customer_id:", customers["customer_id"].duplicated().sum())

Customer rows: 99441
Unique customer_id: 99441
Duplicate customer_id: 0

In [36]:
print("Order rows:", len(orders))
print("Unique customer_id in orders:", orders["customer_id"].nunique())

Order rows: 99441
Unique customer_id in orders: 99441

In [37]:
orders_per_customer = (
    orders
    .groupby("customer_id")
    .size()
    .sort_values(ascending=False)
)

orders_per_customer.head(10)

customer_id
00012a2ce6f8dcda20d059ce98491703    1
000161a058600d5901f007fab4c27140    1
0001fd6190edaaf884bcaf3d49edf079    1
0002414f95344307404f0ace7a26f1d5    1
000379cdec625522490c315e70c7a9fb    1
0004164d20a9e969af783496f3408652    1
000419c5494106c306a97b5635748086    1
00046a560d407e99b969756e0b10f282    1
00050bf6e01e69d5c0fd612f1bcfb69c    1
000598caf2ef4117407665ac33275130    1
dtype: int64

In [38]:
orders_per_customer.value_counts().sort_index()

1    99441
Name: count, dtype: int64

In [39]:
customer_ids = set(customers["customer_id"])

orphan_orders = orders[
    ~orders["customer_id"].isin(customer_ids)
]

print("Orders with unknown customer_id:", len(orphan_orders))

Orders with unknown customer_id: 0

In [40]:
print("Customer rows:", len(customers))
print("Unique customer_id:", customers["customer_id"].nunique())
print("Unique customer_unique_id:", customers["customer_unique_id"].nunique())

Customer rows: 99441
Unique customer_id: 99441
Unique customer_unique_id: 96096

In [41]:
customer_record_counts = (
    customers
    .groupby("customer_unique_id")
    .size()
    .sort_values(ascending=False)
)

customer_record_counts.head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
63cfc61cee11cbe306bff5857d00bfe4     6
dc813062e0fc23409cd255f7f53c7074     6
de34b16117594161a6a89c50b289d35a     6
dtype: int64

In [42]:
print(
    "Customers with multiple customer_id records:",
    (customer_record_counts > 1).sum()
)

Customers with multiple customer_id records: 2997

In [43]:
relationship_summary = pd.DataFrame({
    "metric": [
        "Customer rows",
        "Unique customer_id",
        "Unique customer_unique_id",
        "Order rows",
        "Unique customer_id in orders",
        "Customers with multiple customer_id records",
        "Customers with multiple orders",
        "Orders with unknown customer_id"
    ],
    "value": [
        len(customers),
        customers["customer_id"].nunique(),
        customers["customer_unique_id"].nunique(),
        len(orders),
        orders["customer_id"].nunique(),
        (customer_record_counts > 1).sum(),
        (orders_per_customer > 1).sum(),
        len(orphan_orders)
    ]
})

relationship_summary

                                        metric  value
0                                Customer rows  99441
1                           Unique customer_id  99441
2                    Unique customer_unique_id  96096
3                                   Order rows  99441
4                 Unique customer_id in orders  99441
5  Customers with multiple customer_id records   2997
6               Customers with multiple orders      0
7              Orders with unknown customer_id      0

In [44]:
orders_with_customer = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left",
    validate="one_to_one"
)

In [45]:
validate="one_to_one"

In [46]:
orders_with_customer[
    "customer_unique_id"
].nunique()

96096

In [47]:
orders_per_unique_customer = (
    orders_with_customer
    .groupby("customer_unique_id")
    .size()
    .sort_values(ascending=False)
)

orders_per_unique_customer.head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
63cfc61cee11cbe306bff5857d00bfe4     6
dc813062e0fc23409cd255f7f53c7074     6
de34b16117594161a6a89c50b289d35a     6
dtype: int64

In [48]:
orders_per_unique_customer.value_counts().sort_index()

1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [49]:
orders_with_customer = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left",
    validate="one_to_one"
)

In [50]:
orders_with_customer["customer_unique_id"].nunique()

96096

In [52]:
orders_per_unique_customer = (
    orders_with_customer
    .groupby("customer_unique_id")
    .size()
    .sort_values(ascending=False)
)

orders_per_unique_customer.value_counts().sort_index()

1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [ ]:
orders = tables["olist_orders_dataset"]

orders_profile = profile_table(
    orders,
    "olist_orders_dataset"
)

orders_profile

Table: olist_orders_dataset
Rows: 99,441
Columns: 8
Duplicate rows: 0

,column,dtype,non_null,missing,missing_pct,unique
0,order_id,object,99441,0,0.00,99441
1,customer_id,object,99441,0,0.00,99441
2,order_status,object,99441,0,0.00,8
3,order_purchase_timestamp,object,99441,0,0.00,98875
4,order_approved_at,object,99281,160,0.16,90733
5,order_delivered_carrier_date,object,97658,1783,1.79,81018
6,order_delivered_customer_date,object,96476,2965,2.98,95664
7,order_estimated_delivery_date,object,99441,0,0.00,459

## Customer–Order Relationship Findings

- `customers.customer_id` is unique and can serve as the primary key for the customer-record table.
- Every `orders.customer_id` exists in the customers table; no orphan orders were found.
- `customer_id` occurs only once in the orders table, so it cannot be used to identify repeat purchasing behavior.
- `customer_unique_id` represents the underlying customer across multiple customer records.
- There are 96,096 unique `customer_unique_id` values compared with 99,441 customer records.
- Repeat purchasing must therefore be analyzed using `customer_unique_id`.
- The customer-to-order relationship at the real-customer level is one-to-many.

In [53]:
order_items = tables["olist_order_items_dataset"]

In [54]:
print("Order rows:", len(orders))
print("Order-item rows:", len(order_items))
print("Unique orders in order_items:", order_items["order_id"].nunique())

Order rows: 99441
Order-item rows: 112650
Unique orders in order_items: 98666

In [55]:
items_per_order = (
    order_items
    .groupby("order_id")
    .size()
    .sort_values(ascending=False)
)

items_per_order.head(10)

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
af822dacd6f5cff7376413c03a388bb7    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
dtype: int64

In [56]:
items_per_order.value_counts().sort_index()

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [57]:
order_ids = set(orders["order_id"])

orphan_items = order_items[
    ~order_items["order_id"].isin(order_ids)
]

print("Order items with unknown order_id:", len(orphan_items))

Order items with unknown order_id: 0

In [58]:
orders_with_items = set(order_items["order_id"])

orders_without_items = orders[
    ~orders["order_id"].isin(orders_with_items)
]

print("Orders without order items:", len(orders_without_items))

Orders without order items: 775

In [59]:
items_per_order.value_counts().sort_index()

1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [60]:
order_ids = set(orders["order_id"])

orphan_items = order_items[
    ~order_items["order_id"].isin(order_ids)
]

print("Order items with unknown order_id:", len(orphan_items))

Order items with unknown order_id: 0

In [61]:
orders_with_items = set(order_items["order_id"])

orders_without_items = orders[
    ~orders["order_id"].isin(orders_with_items)
]

print("Orders without order items:", len(orders_without_items))

Orders without order items: 775

In [62]:
orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [63]:
print(
    f"Orders without items: {len(orders_without_items):,}"
)

print(
    f"Percentage of all orders: "
    f"{len(orders_without_items) / len(orders) * 100:.2f}%"
)

Orders without items: 775
Percentage of all orders: 0.78%

In [64]:
payments = tables["olist_order_payments_dataset"]

In [65]:
orders_without_items_payment_check = orders_without_items[
    ["order_id", "order_status"]
].merge(
    payments[["order_id", "payment_value", "payment_type"]],
    on="order_id",
    how="left"
)

orders_without_items_payment_check.head(20)

                            order_id order_status  payment_value payment_type
0   8e24261a7e58791d10cb1bf9da94df5c  unavailable          84.00  credit_card
1   c272bcd21c287498b4883c7512019702  unavailable          97.68  credit_card
2   37553832a3a89c9b2db59701c357ca67  unavailable         132.46       boleto
3   d57e15fb07fd180f06ab3926b39edcd2  unavailable         134.38       boleto
4   00b1cb0320190ca0daa2c88b35206009     canceled           0.00  not_defined
5   2f634e2cebf8c0283e7ef0989f77d217  unavailable         615.53  credit_card
6   ee0db22a8e742b752914016708470ec8  unavailable         167.82  credit_card
7   ed3efbd3a87bea76c2812c66a0b32219     canceled         191.46      voucher
8   6ad57aecbae806a7e9cc2cdb6b380711  unavailable         161.47  credit_card
9   df8282afe61008dc26c6c31011474d02     canceled         139.96       boleto
10  8d4c637f1accf7a88a4555f02741e606     canceled          66.44      voucher
11  9f3458f0433d4cfa472f4682654b8d49  unavailable          78.18  credit_card
12  7a9d4c7f9b068337875b95465330f2fc     canceled          72.90  credit_card
13  f0df036e9be21fc238f131bbfcdde769  unavailable          59.74  credit_card
14  86f0bcd9b426a2c1022ae317c7f27be6  unavailable         177.59  credit_card
15  98fe01bc254b759c1f2c11d77c2891d5  unavailable         150.00      voucher
16  98fe01bc254b759c1f2c11d77c2891d5  unavailable          49.06      voucher
17  f56dc9034c3962e36d49fb73baa12800  unavailable         205.81  credit_card
18  0130f0f71fb0e831d18e6a3b33a3a50c  unavailable          52.77       boleto
19  ddaec6fff982b13e7e048b627a11d6da     canceled         116.99       boleto

In [66]:
payment_coverage = (
    orders_without_items["order_id"]
    .isin(payments["order_id"])
)

print("Orders without items:", len(orders_without_items))
print("Orders without items but with payment:", payment_coverage.sum())
print("Orders without items and without payment:", (~payment_coverage).sum())

Orders without items: 775
Orders without items but with payment: 775
Orders without items and without payment: 0

## Order–Order Item Relationship

- `orders.order_id` is unique within the orders table.
- `order_items.order_id` is not unique because an order can contain multiple items.
- 0 order-item records reference an unknown order.
- Therefore, every order-item record can be associated with a valid order.
- 775 orders do not have corresponding records in `order_items`.
- These 775 orders require further investigation by order status and payment activity before deciding whether they represent expected business cases or data-quality issues.

In [67]:
orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [68]:
print(
    f"Percentage of all orders: "
    f"{len(orders_without_items) / len(orders) * 100:.2f}%"
)

Percentage of all orders: 0.78%

In [69]:
print("Orders without items:", len(orders_without_items))
print("Orders without items but with payment:", payment_coverage.sum())
print("Orders without items and without payment:", (~payment_coverage).sum())

Orders without items: 775
Orders without items but with payment: 775
Orders without items and without payment: 0

In [70]:
orders_without_items[
    orders_without_items["order_status"].isin(["shipped", "invoiced"])
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
23254,a68ce1686d536ca72bd2dadc4b8671e5,d7bed5fac093a4136216072abaf599d5,shipped,2016-10-05 01:47:40,2016-10-07 03:11:22,2016-11-07 16:37:37,NaN,2016-12-01 00:00:00
57591,2ce9683175cdab7d1c95bcbb3e36f478,b2d7ae0415dbbca535b5f7b38056dd1f,invoiced,2016-10-05 21:03:33,2016-10-06 07:46:39,NaN,NaN,2016-11-25 00:00:00
69926,e04f1da1f48bf2bbffcf57b9824f76e1,0d00d77134cae4c58695086ad8d85100,invoiced,2016-10-05 13:22:20,2016-10-06 15:51:38,NaN,NaN,2016-11-29 00:00:00

In [71]:
orders_without_items[
    orders_without_items["order_status"].isin(["shipped", "invoiced"])
][[
    "order_id",
    "customer_id",
    "order_status",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
23254,a68ce1686d536ca72bd2dadc4b8671e5,d7bed5fac093a4136216072abaf599d5,shipped,2016-10-05 01:47:40,2016-10-07 03:11:22,2016-11-07 16:37:37,NaN,2016-12-01 00:00:00
57591,2ce9683175cdab7d1c95bcbb3e36f478,b2d7ae0415dbbca535b5f7b38056dd1f,invoiced,2016-10-05 21:03:33,2016-10-06 07:46:39,NaN,NaN,2016-11-25 00:00:00
69926,e04f1da1f48bf2bbffcf57b9824f76e1,0d00d77134cae4c58695086ad8d85100,invoiced,2016-10-05 13:22:20,2016-10-06 15:51:38,NaN,NaN,2016-11-29 00:00:00

In [72]:
payments[
    payments["order_id"].isin(
        orders_without_items[
            orders_without_items["order_status"].isin(
                ["shipped", "invoiced"]
            )
        ]["order_id"]
    )
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
75617,2ce9683175cdab7d1c95bcbb3e36f478,1,boleto,1,73.04
88900,a68ce1686d536ca72bd2dadc4b8671e5,1,boleto,1,77.73
99415,e04f1da1f48bf2bbffcf57b9824f76e1,1,credit_card,7,76.19

In [73]:
products = tables["olist_products_dataset"]

In [74]:
print("Order-item rows:", len(order_items))
print("Unique product_id in order_items:", order_items["product_id"].nunique())

print("Product rows:", len(products))
print("Unique product_id in products:", products["product_id"].nunique())

Order-item rows: 112650
Unique product_id in order_items: 32951
Product rows: 32951
Unique product_id in products: 32951

In [75]:
product_ids = set(products["product_id"])

orphan_product_items = order_items[
    ~order_items["product_id"].isin(product_ids)
]

print(
    "Order items with unknown product_id:",
    len(orphan_product_items)
)

Order items with unknown product_id: 0

In [76]:
sellers = tables["olist_sellers_dataset"]

In [77]:
print("Seller rows:", len(sellers))
print("Unique seller_id:", sellers["seller_id"].nunique())
print("Unique seller_id in order_items:", order_items["seller_id"].nunique())

Seller rows: 3095
Unique seller_id: 3095
Unique seller_id in order_items: 3095

In [79]:
seller_ids = set(sellers["seller_id"])

orphan_seller_items = order_items[
    ~order_items["seller_id"].isin(seller_ids)
]

print(
    "Order items with unknown seller_id:",
    len(orphan_seller_items)
)

Order items with unknown seller_id: 0

## Order Item Relationships

### Order → Order Items

- `orders.order_id` is unique in the orders table.
- `order_items.order_id` is non-unique because one order can contain multiple items.
- 0 order items reference an unknown order.
- 775 orders have no order-item records.
- The 775 orders represent 0.78% of all orders and are predominantly `unavailable` or `canceled`.
- These orders are retained and will be handled according to the analytical use case.

### Order Item → Product

- Every `order_items.product_id` exists in `products.product_id`.
- No orphan product references were found.
- `products.product_id` is unique in the product table.

### Order Item → Seller

- Every `order_items.seller_id` exists in `sellers.seller_id`.
- No orphan seller references were found.
- `sellers.seller_id` is unique in the seller table.

In [80]:
order_items["order_item_id"].value_counts().sort_index()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [81]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [82]:
duplicate_order_items = order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

print(
    "Duplicate (order_id, order_item_id) combinations:",
    duplicate_order_items
)

Duplicate (order_id, order_item_id) combinations: 0

In [83]:
print(
    "Unique order_id + order_item_id combinations:",
    order_items[["order_id", "order_item_id"]].drop_duplicates().shape[0]
)

print(
    "Total order-item rows:",
    len(order_items)
)

Unique order_id + order_item_id combinations: 112650
Total order-item rows: 112650

In [84]:
order_items["order_item_id"].value_counts()

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [85]:
duplicate_order_items = order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

print(
    "Duplicate (order_id, order_item_id) combinations:",
    duplicate_order_items
)

Duplicate (order_id, order_item_id) combinations: 0

In [86]:
print(
    "Total order-item rows:",
    len(order_items)
)

print(
    "Unique (order_id, order_item_id) combinations:",
    order_items[
        ["order_id", "order_item_id"]
    ].drop_duplicates().shape[0]
)

Total order-item rows: 112650
Unique (order_id, order_item_id) combinations: 112650